name: 'Add assets to release'
permissions:
  contents: 'write'
'on':
  release:
    types: ['published']
concurrency:
  group: 'release'
defaults:
  run:
    shell: 'bash'
jobs:
  publish_asstes:
    name: 'Publish Assets'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # v7.0.0
      - uses: 'extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b' # v3
      - name: 'Publish Assets'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          just build-all "${GITHUB_REF#refs/tags/}"
          just publish-assets "${GITHUB_REF#refs/tags/}"
